rng:
    build: dockerfiles/rng
    environment:
      - TELEMETRY_AGENT=Console
      - NAMESPACE=foo
    ports:
      - "8001:80"

hasher:
    build: dockerfiles/hasher
    ports:
      - "8002:80"

webui:
    build: dockerfiles/webui
    links:
      - redis
    ports:
      - "8000:80"
    volumes:
      - "./dockerfiles/webui/files/:/files/"

redis:
    image: dockerfiles/redis

worker:
    build: dockerfiles/worker
    environment:
      - TELEMETRY_AGENT=Console
      - NAMESPACE=foo
    links:
      - rng
      - hasher
      - redis

